import type { ProductImportItem } from '../repositories/product-repository'

/** Core product fields extracted from Харчування.xlsx. */
export const FIT_KITCHEN_CATALOG: ProductImportItem[] = [
  {"sourceKey":"fitkitchen-row-4","name":"Куряче філе","category":"Білкові продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-5","name":"Філе лосося без шкіри","category":"Білкові продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-6","name":"Сироватковий протеїн","category":"Білкові продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-7","name":"Креветки 70/90","category":"Білкові продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-8","name":"Фарш індички","category":"Білкові продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-9","name":"Яйця","category":"Білкові продукти","baseUnit":"pcs"},
  {"sourceKey":"fitkitchen-row-10","name":"Філе форелі заморожене","category":"Білкові продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-11","name":"Яловичий фарш 5%","category":"Білкові продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-12","name":"Натуральний протеїновий йогурт","category":"Молочні продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-13","name":"Зернений сир","category":"Молочні продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-14","name":"Сир Jarlsberg","category":"Молочні продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-15","name":"Моцарела","category":"Молочні продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-16","name":"Пармезан","category":"Молочні продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-17","name":"Крем-сир Philadelphia Light","category":"Молочні продукти","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-18","name":"Молоко 1%","category":"Молочні продукти","baseUnit":"ml"},
  {"sourceKey":"fitkitchen-row-19","name":"Buldak Carbonara","category":"Крупи та основи","baseUnit":"pcs"},
  {"sourceKey":"fitkitchen-row-20","name":"Цільнозерновий хліб","category":"Крупи та основи","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-21","name":"Рис","category":"Крупи та основи","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-22","name":"Основа Pinsa, 2 шт.","category":"Крупи та основи","baseUnit":"pcs"},
  {"sourceKey":"fitkitchen-row-23","name":"Великі тортильї","category":"Крупи та основи","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-24","name":"Вівсяні пластівці","category":"Крупи та основи","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-25","name":"Гранола","category":"Крупи та основи","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-26","name":"Цільнозернова паста","category":"Крупи та основи","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-27","name":"Рис для суші","category":"Крупи та основи","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-28","name":"Панірувальні сухарі","category":"Крупи та основи","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-29","name":"Броколі","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-30","name":"Огірок","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-31","name":"Помідори вагові","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-32","name":"Авокадо, 2 шт.","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-33","name":"Салат айсберг / мікс","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-34","name":"Картопля","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-35","name":"Шпинат митий","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-36","name":"Помідори чері","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-37","name":"Солодкий червоний перець","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-38","name":"Рукола мита","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-39","name":"Морква","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-40","name":"Зелена цибуля","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-41","name":"Печериці","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-42","name":"Жовта цибуля","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-43","name":"Лимон","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-44","name":"Часник","category":"Овочі та зелень","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-45","name":"Заморожена суміш ягід","category":"Фрукти та ягоди","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-46","name":"Банани","category":"Фрукти та ягоди","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-47","name":"Норі для суші","category":"Соуси, олії та добавки","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-48","name":"Соєвий соус","category":"Соуси, олії та добавки","baseUnit":"ml"},
  {"sourceKey":"fitkitchen-row-49","name":"Оливкова олія extra virgin","category":"Соуси, олії та добавки","baseUnit":"ml"},
  {"sourceKey":"fitkitchen-row-50","name":"Мед","category":"Соуси, олії та добавки","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-51","name":"Сальса","category":"Соуси, олії та добавки","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-52","name":"Соус теріякі","category":"Соуси, олії та добавки","baseUnit":"ml"},
  {"sourceKey":"fitkitchen-row-53","name":"Легке кокосове молоко","category":"Соуси, олії та добавки","baseUnit":"ml"},
  {"sourceKey":"fitkitchen-row-54","name":"Pesto alla Genovese","category":"Соуси, олії та добавки","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-55","name":"Насіння чіа","category":"Соуси, олії та добавки","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-56","name":"Горіхи","category":"Соуси, олії та добавки","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-57","name":"Паста карі","category":"Соуси, олії та добавки","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-58","name":"Кунжут","category":"Соуси, олії та добавки","baseUnit":"g"},
  {"sourceKey":"fitkitchen-row-59","name":"Рисовий оцет","category":"Соуси, олії та добавки","baseUnit":"ml"},
]
